name: Build and publish docker image

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build and publish docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        id: push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/tinfoilanalytics/eif-builder:${{ github.sha }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/tinfoilanalytics/eif-builder:${{ github.sha }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
